image: ubuntu/latest
packages:
    - curl
    - unzip
sources:
    - https://git.sr.ht/~ruivieira/deno-experiments
tasks:
    - setup: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export PATH=$PATH:~/.deno/bin
    - test: |
        cd deno-experiments
        deno deno fmt --check */**.ts
        deno test