name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
      - name: Show Deno version
        run: deno --version
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test
